name: flutter_berita_app
description: Aplikasi berita menggunakan Flutter dan CodeIgniter 4
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  http_parser: ^4.0.2
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  flutter_html: ^3.0.0-beta.2
  shimmer: ^3.0.0
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500 